# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18krWZe_msFO14S8MIzwLOmt5-dIRUNO8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Analysis and Visualization
def analyze_and_plot_data():
    data = {
        'Cryptocurrency': ['Bitcoin', 'Ethereum', 'Ripple', 'Litecoin', 'Cardano'],
        'Price': [50000, 4000, 1.2, 200, 1.5],
        '24h Change (%)': [2.5, -1.2, 0.8, -0.3, 1.0]
    }
    df = pd.DataFrame(data)

    plt.figure(figsize=(8, 6))
    sns.barplot(x='Cryptocurrency', y='Price', data=df)
    plt.title('Cryptocurrency Prices')
    plt.show()