# -*- coding: utf-8 -*-
"""data_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18krWZe_msFO14S8MIzwLOmt5-dIRUNO8
"""

import requests
from tkinter import messagebox

# Fetch Crypto Data from CoinGecko API
def fetch_crypto_data(coin):
    url = f"https://api.coingecko.com/api/v3/coins/{coin}"
    try:
        response = requests.get(url)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        messagebox.showerror("Error", f"Unable to fetch cryptocurrency data: {e}")
        return None