# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18krWZe_msFO14S8MIzwLOmt5-dIRUNO8
"""

import tkinter as tk
from tkinter import ttk, messagebox
from data_fetch import fetch_crypto_data
from data_analysis import analyze_and_plot_data
from threading import Thread

# Display Cryptocurrency Data in GUI
def display_crypto_data():
    coin = crypto_combobox.get().lower().replace(" ", "-")
    if not coin:
        messagebox.showwarning("Input Error", "Please select a cryptocurrency.")
        return
    result_label.config(text="Fetching crypto data...")
    Thread(target=lambda: update_crypto_data(fetch_crypto_data(coin))).start()

# Cryptocurrency Data on GUI
def update_crypto_data(data):
    if data:
        price = data['market_data']['current_price']['usd']
        change = data['market_data']['price_change_percentage_24h']
        crypto_info = f"{data['name']}:\nPrice: ${price:.2f}\n24h Change: {change:.2f}%"
        result_label.config(text=crypto_info)

# GUI
root = tk.Tk()
root.title("Custom Intelligent Application")
root.geometry("600x400")

tab_control = ttk.Notebook(root)

# Tab 1: Cryptocurrency Data
crypto_tab = ttk.Frame(tab_control)
tab_control.add(crypto_tab, text='Cryptocurrency Data')

tk.Label(crypto_tab, text="Select a Cryptocurrency:", font=("Arial", 14)).pack(pady=10)
crypto_combobox = ttk.Combobox(crypto_tab, values=['Bitcoin', 'Ethereum', 'Ripple', 'Litecoin', 'Cardano'])
crypto_combobox.pack(pady=5)
tk.Button(crypto_tab, text="Fetch Crypto", command=display_crypto_data).pack(pady=10)

# Tab 2: Data Analysis
analysis_tab = ttk.Frame(tab_control)
tab_control.add(analysis_tab, text='Data Analysis')

tk.Button(analysis_tab, text="Analyze and Plot Data", command=analyze_and_plot_data).pack(pady=20)

# Result Display Section
result_label = tk.Label(root, text="", font=("Arial", 12), justify="left")
result_label.pack(pady=20)

tab_control.pack(expand=1, fill='both')

root.mainloop()